server:
  port: 18081

spring:
  application:
    name: account-server
  zipkin:
    base-url: http://localhost:19411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/