
server:
  port: 18762
spring:
  application:
    name: eureka-server1
  zipkin:
    base-url: http://localhost:19411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
