

server:
  port: 18080

spring:
  application:
    name: user-server
  zipkin:
    base-url: http://localhost:19411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
