
server:
  port: 18761
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:19411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18762/eureka/;